### ISSUE TITLE
Links to module documentation not work.

### ISSUE THREAD

**Issue by arisudi** [cuzy-app/humhub-modules-external-websites#1]
Links to module documentation Not Found:
https://github.com/cuzy-app/humhub-modules-external-websites/-/raw/master/docs/examples/external-website-page-embedding-humhub-addons.php

**Comment by marc-farre** [comment]
Thanks! Fixed in commit https://github.com/cuzy-app/humhub-modules-external-websites/commit/8c6abacc068d2d41f3ea36b1a212cdbce9544a23
